package Frames;


import BeanClasses.FacultyBean;
import DatabaseManager.DatabaseManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danish
 */
public class FacultyFrame extends javax.swing.JFrame{

    /**
     * Creates new form FacultyFrame
     */
    public FacultyFrame() {
        initComponents();
        getFaculty();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyLabel = new javax.swing.JLabel();
        facIdLabel = new javax.swing.JLabel();
        facNameLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        facIdTextField = new javax.swing.JTextField();
        facNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        facultyListLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        facultyList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1200));
        getContentPane().setLayout(null);

        facultyLabel.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        facultyLabel.setText("FACULTY");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(490, 50, 290, 70);

        facIdLabel.setText("FACULTY ID");
        getContentPane().add(facIdLabel);
        facIdLabel.setBounds(130, 200, 90, 20);

        facNameLabel.setText("FACULTY NAME");
        getContentPane().add(facNameLabel);
        facNameLabel.setBounds(130, 250, 120, 40);

        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(130, 320, 70, 20);

        facIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(facIdTextField);
        facIdTextField.setBounds(280, 190, 490, 40);
        getContentPane().add(facNameTextField);
        facNameTextField.setBounds(280, 250, 490, 40);

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 320, 490, 200);

        facultyListLabel.setText("FACULTIES");
        getContentPane().add(facultyListLabel);
        facultyListLabel.setBounds(800, 270, 120, 30);

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(280, 550, 100, 50);

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(410, 550, 110, 50);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(560, 550, 100, 50);

        backButton.setText("BACK");
        backButton.setPreferredSize(new java.awt.Dimension(2000, 1200));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(690, 550, 90, 50);

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(1050, 539, 120, 50);

        facultyList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                facultyListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(facultyList);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(800, 320, 400, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facIdTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
         if(updateButton==evt.getSource())  
                updateFaculty(); // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
            if(addButton==evt.getSource())  
                addFaculty(); // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed
private void getFaculty(){
	try{
		java.util.Vector v=DatabaseManager.getFaculty();		
                facultyList.setListData(v);
	}catch(Exception e){
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}//end Method 
    private void addFaculty(){
    String facName=facNameTextField.getText();
    String remarks=remarksTextArea.getText();

    try{
               	int rows=DatabaseManager.addFaculty(facName,remarks);
	if(rows>=1){
	        	javax.swing.JOptionPane.showMessageDialog(this,rows+" Records Inserted."); 
		clear();
		getFaculty();				
	}
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}   //end 
private void deleteFaculty(){
    FacultyBean bean = (FacultyBean)facultyList.getSelectedValue();
    if(bean==null)return;
    try{
           int rows = DatabaseManager.deleteFaculty(bean.getFacId());
           if(rows>=1){
           javax.swing.JOptionPane.showMessageDialog(this,rows+"Rrecord Removed.");
           getFaculty();
           clear();
           }
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}

private void updateFaculty(){
     FacultyBean bean=(FacultyBean)facultyList.getSelectedValue();
     if(bean==null)return;

     String facName=facNameTextField.getText();
     String remarks=remarksTextArea.getText();

     try{
	int rows=DatabaseManager.updateFaculty(bean.getFacId(),facName,remarks);
	if(rows>=1){
	    javax.swing.JOptionPane.showMessageDialog(this,rows+" Record Modified.");
	    getFaculty();
	    clear();
        	}
     }catch(Exception e){
         e.printStackTrace();
         javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
     } 
}
private void clear(){
    facIdTextField.setText("");
    facNameTextField.setText("");
    remarksTextArea.setText("");
}
    private void facultyListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_facultyListValueChanged
       FacultyBean bean=(FacultyBean)facultyList.getSelectedValue();
   if(bean==null)return;

   facIdTextField.setText( ""+bean.getFacId());
   facNameTextField.setText( bean.getFacName());
   remarksTextArea.setText( bean.getRemarks());        // TODO add your handling code here:
    }//GEN-LAST:event_facultyListValueChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(deleteButton==evt.getSource())  
            deleteFaculty();
            // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    clear();        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
//          new MainFrame().setVisible(true);
//          dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel facIdLabel;
    private javax.swing.JTextField facIdTextField;
    private javax.swing.JLabel facNameLabel;
    private javax.swing.JTextField facNameTextField;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JList facultyList;
    private javax.swing.JLabel facultyListLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
