/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;

/**
 *
 * @author Danish
 */
public class HomeFrame extends javax.swing.JFrame {


    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        facultyLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        progLabel = new javax.swing.JLabel();
        batchLabel = new javax.swing.JLabel();
        stdLabel = new javax.swing.JLabel();
        bookLabel = new javax.swing.JLabel();
        bookIssueLabel = new javax.swing.JLabel();
        defaulterLabel = new javax.swing.JLabel();
        libraryPicLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBackground(new java.awt.Color(102, 0, 102));
        dashboardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        facultyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        facultyLabel.setForeground(new java.awt.Color(240, 240, 240));
        facultyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/faculty_1.png"))); // NOI18N
        facultyLabel.setText("Faculty");
        facultyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultyLabelMouseClicked(evt);
            }
        });

        deptLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deptLabel.setForeground(new java.awt.Color(240, 240, 240));
        deptLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/department_1.png"))); // NOI18N
        deptLabel.setText("Department");
        deptLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptLabelMouseClicked(evt);
            }
        });

        progLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progLabel.setForeground(new java.awt.Color(240, 240, 240));
        progLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/program_1.png"))); // NOI18N
        progLabel.setText("Program");
        progLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progLabelMouseClicked(evt);
            }
        });

        batchLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        batchLabel.setForeground(new java.awt.Color(240, 240, 240));
        batchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/batch_1.png"))); // NOI18N
        batchLabel.setText("Batch");
        batchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchLabelMouseClicked(evt);
            }
        });

        stdLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        stdLabel.setForeground(new java.awt.Color(240, 240, 240));
        stdLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student_1.png"))); // NOI18N
        stdLabel.setText("Student");
        stdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdLabelMouseClicked(evt);
            }
        });

        bookLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bookLabel.setForeground(new java.awt.Color(240, 240, 240));
        bookLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book_1.png"))); // NOI18N
        bookLabel.setText("Book");
        bookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookLabelMouseClicked(evt);
            }
        });

        bookIssueLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bookIssueLabel.setForeground(new java.awt.Color(240, 240, 240));
        bookIssueLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookIssue_1.png"))); // NOI18N
        bookIssueLabel.setText("Book Issue");
        bookIssueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookIssueLabelMouseClicked(evt);
            }
        });

        defaulterLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        defaulterLabel.setForeground(new java.awt.Color(240, 240, 240));
        defaulterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/defaulterList_1.png"))); // NOI18N
        defaulterLabel.setText("Defaulter List");
        defaulterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaulterLabelMouseClicked(evt);
            }
        });

        libraryPicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Library4.jpg"))); // NOI18N

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(libraryPicLabel))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defaulterLabel)
                            .addComponent(bookIssueLabel)
                            .addComponent(bookLabel)
                            .addComponent(stdLabel)
                            .addComponent(batchLabel)
                            .addComponent(progLabel)
                            .addComponent(deptLabel)
                            .addComponent(facultyLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libraryPicLabel)
                .addGap(70, 70, 70)
                .addComponent(facultyLabel)
                .addGap(41, 41, 41)
                .addComponent(deptLabel)
                .addGap(55, 55, 55)
                .addComponent(progLabel)
                .addGap(48, 48, 48)
                .addComponent(batchLabel)
                .addGap(58, 58, 58)
                .addComponent(stdLabel)
                .addGap(53, 53, 53)
                .addComponent(bookLabel)
                .addGap(44, 44, 44)
                .addComponent(bookIssueLabel)
                .addGap(60, 60, 60)
                .addComponent(defaulterLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setText("Library Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2097, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addComponent(dashboardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultyLabelMouseClicked
      facultyLabel.setForeground(new Color(120, 90, 40));
      facultyLabel.setOpaque(true);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(false);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
      defaulterLabel.setBackground(Color.white);   
      defaulterLabel.setForeground(Color.white);
      defaulterLabel.setOpaque(false); 
      
      
      
        FacultyPanel facPanel=new FacultyPanel(); 
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(facPanel);
            jPanel1.repaint();
            jPanel1.revalidate();

    }//GEN-LAST:event_facultyLabelMouseClicked

    private void deptLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setForeground(new Color(120, 90, 40));
      deptLabel.setOpaque(true);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(false);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
      defaulterLabel.setBackground(Color.white);   
      defaulterLabel.setForeground(Color.white);
      defaulterLabel.setOpaque(false);      
        
        DepartmentPanel deptPanel=new DepartmentPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(deptPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_deptLabelMouseClicked

    private void progLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
     
      progLabel.setForeground(new Color(120, 90, 40));
      progLabel.setOpaque(true);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(false);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
      defaulterLabel.setBackground(Color.white);   
      defaulterLabel.setForeground(Color.white);
     defaulterLabel.setOpaque(false);    
        
        ProgramPanel progPanel=new ProgramPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(progPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_progLabelMouseClicked

    private void batchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
     
      batchLabel.setForeground(new Color(120, 90, 40));
      batchLabel.setOpaque(true);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(false);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
      defaulterLabel.setBackground(Color.white);   
      defaulterLabel.setForeground(Color.white);
      defaulterLabel.setOpaque(false);         
        
        BatchPanel batchPanel=new BatchPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(batchPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_batchLabelMouseClicked

    private void stdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      
      stdLabel.setForeground(new Color(120, 90, 40));
      stdLabel.setOpaque(true);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(false);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
      defaulterLabel.setBackground(Color.white);   
      defaulterLabel.setForeground(Color.white);
      defaulterLabel.setOpaque(false);       
        
        StudentPanel stdPanel=new StudentPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(stdPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_stdLabelMouseClicked

    private void bookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
     
      bookLabel.setForeground(new Color(120, 90, 40));
      bookLabel.setOpaque(true);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
      defaulterLabel.setBackground(Color.white);   
       defaulterLabel.setForeground(Color.white);
      defaulterLabel.setOpaque(false);             
        
        BookPanel bookPanel=new BookPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(bookPanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_bookLabelMouseClicked

    private void bookIssueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookIssueLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(false);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(false);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(false);
      
      
      bookIssueLabel.setForeground(new Color(120, 90, 40));
      bookIssueLabel.setOpaque(true);
      
      defaulterLabel.setBackground(Color.white);   
      defaulterLabel.setForeground(Color.white);
      defaulterLabel.setOpaque(false);         
        
        BookIssuePanel bookIssuePanel=new BookIssuePanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(bookIssuePanel);
            jPanel1.repaint();
            jPanel1.revalidate();
    }//GEN-LAST:event_bookIssueLabelMouseClicked

    private void defaulterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaulterLabelMouseClicked
      facultyLabel.setBackground(Color.white);
      facultyLabel.setForeground(Color.white);
      facultyLabel.setOpaque(false);
      
      deptLabel.setBackground(Color.white);
      deptLabel.setForeground(Color.white);
      deptLabel.setOpaque(false);
      
      progLabel.setBackground(Color.white);
      progLabel.setForeground(Color.white);
      progLabel.setOpaque(false);    
      
      batchLabel.setBackground(Color.white);
      batchLabel.setForeground(Color.white);
      batchLabel.setOpaque(true);
      
      stdLabel.setBackground(Color.white);
      stdLabel.setForeground(Color.white);
      stdLabel.setOpaque(true);
      
      bookLabel.setBackground(Color.white);
      bookLabel.setForeground(Color.white);
      bookLabel.setOpaque(true);
      
      bookIssueLabel.setBackground(Color.white);
      bookIssueLabel.setForeground(Color.white);
      bookIssueLabel.setOpaque(false);
      
         
      defaulterLabel.setForeground(new Color(120, 90, 40));
      defaulterLabel.setOpaque(true); 
      
        DefaulterListPanel defaulterListPanel=new DefaulterListPanel();
        //removing panel
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            //adding panel
            jPanel1.add(defaulterListPanel);
            jPanel1.repaint();
            jPanel1.revalidate();        
    }//GEN-LAST:event_defaulterLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batchLabel;
    private javax.swing.JLabel bookIssueLabel;
    private javax.swing.JLabel bookLabel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel defaulterLabel;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel libraryPicLabel;
    private javax.swing.JLabel progLabel;
    private javax.swing.JLabel stdLabel;
    // End of variables declaration//GEN-END:variables
}
