package Frames;


import BeanClasses.BatchBean;
import BeanClasses.DepartmentBean;
import BeanClasses.FacultyBean;
import BeanClasses.ListItem;
import BeanClasses.ProgramBean;
import BeanClasses.StudentBean;
import DatabaseManager.DatabaseManager;
import EnDeCoder.Decoder;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Danish
 */
public class StudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
      
        	genderComboBox.addItem(new ListItem("M","MALE"));
		genderComboBox.addItem(new ListItem("F","FEMALE"));
                
                  getFaculty();
    }
  private void getFaculty(){
	try{
                Vector v=DatabaseManager.getFaculty();
		facultyComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			facultyComboBox.addItem(v.elementAt(i));

	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}//end method
  private void getDepartment(){
	FacultyBean bean=(FacultyBean)facultyComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getDepartment( bean.getFacId() );
	      deptComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			deptComboBox.addItem(v.elementAt(i));	
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}
  private void getProgram(){
	DepartmentBean bean=(DepartmentBean)deptComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getProgram( bean.getDeptId() );
	          progComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			progComboBox.addItem(v.elementAt(i));	
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}  
  private void getBatch(){
	ProgramBean bean=(ProgramBean)progComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getBatch( bean.getProgId() );
	        batchYearComboBox.removeAllItems();
		for(int i=0; i<v.size(); i++)
			batchYearComboBox.addItem(v.elementAt(i));		
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}     
  private void getShiftGroup()
        {
            BatchBean bean=(BatchBean)batchYearComboBox.getSelectedItem();
            if(bean==null)return;
         
            String shift = Decoder.shiftDecode(bean.getShift());
            String group = Decoder.groupDecode(bean.getGroupDesc());
            
            shiftTextField.setText(shift);
              groupTextField.setText(group);
        } 
 private void getStudent(){
	BatchBean bean=(BatchBean)batchYearComboBox.getSelectedItem();
	if(bean==null)return;

	try{
	          Vector v=DatabaseManager.getStudent( bean.getBatchId() );
	         rollNoList.setListData(v);
				
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stdLabel = new javax.swing.JLabel();
        facultyLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        progLabel = new javax.swing.JLabel();
        batchYearLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        stdIdLabel = new javax.swing.JLabel();
        rollNoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        rollNoListLabel = new javax.swing.JLabel();
        facultyComboBox = new javax.swing.JComboBox();
        deptComboBox = new javax.swing.JComboBox();
        progComboBox = new javax.swing.JComboBox();
        batchYearComboBox = new javax.swing.JComboBox();
        shiftTextField = new javax.swing.JTextField();
        groupTextField = new javax.swing.JTextField();
        stdIdTextField = new javax.swing.JTextField();
        rollNoTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        fnameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        rollNoList = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2000, 1000));
        getContentPane().setLayout(null);

        stdLabel.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        stdLabel.setText("STUDENT REGISTRATION");
        getContentPane().add(stdLabel);
        stdLabel.setBounds(320, 39, 670, 60);

        facultyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        facultyLabel.setText("FACULTY");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(90, 140, 140, 40);

        deptLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deptLabel.setText("DEPARTMENT");
        getContentPane().add(deptLabel);
        deptLabel.setBounds(40, 190, 170, 40);

        progLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progLabel.setText("PROGRAMS");
        getContentPane().add(progLabel);
        progLabel.setBounds(70, 240, 138, 40);

        batchYearLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        batchYearLabel.setText("BATCH YEAR");
        getContentPane().add(batchYearLabel);
        batchYearLabel.setBounds(50, 290, 160, 40);

        shiftLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        shiftLabel.setText("SHIFT");
        getContentPane().add(shiftLabel);
        shiftLabel.setBounds(390, 290, 80, 40);

        groupLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        groupLabel.setText("GROUP");
        getContentPane().add(groupLabel);
        groupLabel.setBounds(600, 290, 90, 40);

        stdIdLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        stdIdLabel.setText("STUDENT ID");
        getContentPane().add(stdIdLabel);
        stdIdLabel.setBounds(50, 340, 160, 40);

        rollNoLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rollNoLabel.setText("ROLL NO");
        getContentPane().add(rollNoLabel);
        rollNoLabel.setBounds(90, 400, 110, 40);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameLabel.setText("NAME ");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(120, 450, 80, 40);

        fnameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fnameLabel.setText("FATHER NAME ");
        getContentPane().add(fnameLabel);
        fnameLabel.setBounds(20, 500, 180, 40);

        surnameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        surnameLabel.setText("SURNAME");
        getContentPane().add(surnameLabel);
        surnameLabel.setBounds(70, 550, 130, 40);

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        genderLabel.setText("GENDER");
        getContentPane().add(genderLabel);
        genderLabel.setBounds(460, 550, 120, 40);

        remarksLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(70, 600, 130, 40);

        rollNoListLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rollNoListLabel.setText("ROLL NO");
        getContentPane().add(rollNoListLabel);
        rollNoListLabel.setBounds(850, 130, 140, 40);

        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(facultyComboBox);
        facultyComboBox.setBounds(230, 140, 600, 40);

        deptComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(deptComboBox);
        deptComboBox.setBounds(230, 190, 600, 40);

        progComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(progComboBox);
        progComboBox.setBounds(230, 240, 600, 40);

        batchYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchYearComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(batchYearComboBox);
        batchYearComboBox.setBounds(230, 290, 150, 40);

        shiftTextField.setEditable(false);
        getContentPane().add(shiftTextField);
        shiftTextField.setBounds(470, 290, 120, 40);

        groupTextField.setEditable(false);
        getContentPane().add(groupTextField);
        groupTextField.setBounds(690, 290, 140, 40);
        getContentPane().add(stdIdTextField);
        stdIdTextField.setBounds(230, 350, 150, 40);
        getContentPane().add(rollNoTextField);
        rollNoTextField.setBounds(230, 400, 370, 40);
        getContentPane().add(nameTextField);
        nameTextField.setBounds(230, 450, 370, 40);
        getContentPane().add(fnameTextField);
        fnameTextField.setBounds(230, 500, 370, 40);
        getContentPane().add(surnameTextField);
        surnameTextField.setBounds(230, 550, 210, 40);

        getContentPane().add(genderComboBox);
        genderComboBox.setBounds(590, 550, 170, 40);

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 610, 610, 170);

        rollNoList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rollNoListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(rollNoList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(850, 170, 320, 610);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(230, 810, 130, 50);

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(370, 810, 160, 50);

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(540, 810, 150, 50);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(700, 810, 140, 50);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(850, 810, 320, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
    getDepartment();        // TODO add your handling code here:
    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void deptComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptComboBoxActionPerformed
    getProgram();        // TODO add your handling code here:
    }//GEN-LAST:event_deptComboBoxActionPerformed

    private void progComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progComboBoxActionPerformed
    getBatch();        // TODO add your handling code here:
    }//GEN-LAST:event_progComboBoxActionPerformed

    private void batchYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchYearComboBoxActionPerformed
 
        getShiftGroup();
        getStudent();        // TODO add your handling code here:
    }//GEN-LAST:event_batchYearComboBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(addButton==evt.getSource())
            addStudent();// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void rollNoListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rollNoListValueChanged
                                             
   StudentBean bean=(StudentBean)rollNoList.getSelectedValue();
   if(bean==null)return;

   stdIdTextField.setText( ""+bean.getStdId());
   rollNoTextField.setText( bean.getRollNo());
   nameTextField.setText( bean.getName());
   fnameTextField.setText( bean.getFname());
   surnameTextField.setText( bean.getSurname());
   genderComboBox.setSelectedItem( bean.getGender());
   getShiftGroup();
  // shiftTextField.setText( bean.getShift());
   // groupTextField.setText( bean.getGroup());
   remarksTextArea.setText( bean.getRemarks());        // TODO add your handling code here:
 
      for(int i=0; i<genderComboBox.getItemCount(); i++){
	ListItem item=(ListItem)genderComboBox.getItemAt(i);
	if(item.getKey().equals(bean.getGender()))
		genderComboBox.setSelectedItem(item);
}
    }//GEN-LAST:event_rollNoListValueChanged

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
            if(clearButton==evt.getSource())
            clear();        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
         if(deleteButton==evt.getSource())
            deleteStudent();        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
            if(updateButton==evt.getSource())  
                updateStudent();        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
//          new MainFrame().setVisible(true);
//          dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed
private void addStudent(){
     BatchBean bean=(BatchBean)batchYearComboBox.getSelectedItem();
     if(bean==null)return;

     String  rollNo = rollNoTextField.getText();
     String name = nameTextField.getText();
    String fname=fnameTextField.getText();
    String surname=surnameTextField.getText();
    ListItem genderItem=(ListItem)genderComboBox.getSelectedItem();
    String remarks=remarksTextArea.getText();

    try{
               	int rows=DatabaseManager.addStudent(bean.getBatchId(),name,fname,surname,rollNo,genderItem.getKey(),remarks);
	if(rows>=1){
	        	javax.swing.JOptionPane.showMessageDialog(this,rows+" Records Inserted."); 
		clear();
		getStudent();				
	}
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}   //end
private void deleteStudent(){
    StudentBean bean = (StudentBean)rollNoList.getSelectedValue();
    if(bean==null)return;
    try{
           int rows = DatabaseManager.deleteStudent(bean.getStdId());
           if(rows>=1){
           javax.swing.JOptionPane.showMessageDialog(this,rows+"Record Removed.");
           getStudent();
           clear();
           }
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}
private void updateStudent(){
     StudentBean bean=(StudentBean)rollNoList.getSelectedValue();
     if(bean==null)return;

    String  rollNo = rollNoTextField.getText();
    String stdName = nameTextField.getText();
    String fName=fnameTextField.getText();
    String surname=surnameTextField.getText();
    String remarks=remarksTextArea.getText();
     try{
	int rows=DatabaseManager.updateStudent(bean.getStdId(),stdName,fName,surname,rollNo,remarks);
	if(rows>=1){
	    javax.swing.JOptionPane.showMessageDialog(this,rows+" Record Modified.");
	    getStudent();
	    clear();
        	}
     }catch(Exception e){
         e.printStackTrace();
         javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
     } 
}

private void clear(){
    stdIdTextField.setText("");
    rollNoTextField.setText("");
    nameTextField.setText("");
    fnameTextField.setText("");
    surnameTextField.setText("");
    remarksTextArea.setText("");
} 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox batchYearComboBox;
    private javax.swing.JLabel batchYearLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox deptComboBox;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JComboBox facultyComboBox;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JTextField groupTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox progComboBox;
    private javax.swing.JLabel progLabel;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JLabel rollNoLabel;
    private javax.swing.JList rollNoList;
    private javax.swing.JLabel rollNoListLabel;
    private javax.swing.JTextField rollNoTextField;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JTextField shiftTextField;
    private javax.swing.JLabel stdIdLabel;
    private javax.swing.JTextField stdIdTextField;
    private javax.swing.JLabel stdLabel;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
